## Working with numpy for mathematical operations

In [3]:
import numpy as np

a=np.array([1,2,3,4,5])

print(a)
# this is 1-D array can be accessed using a[0],a[1],....
print(a.shape)

print(type(a))

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


In [4]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(type(b))

# this is 2D array can be accessed b[0][0],b[1][0]....

print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
<class 'numpy.ndarray'>
(5, 1)


In [7]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

print(c.shape)
print(c[1][1])
print(type(c))

[[1 2 3]
 [4 5 6]]
(2, 3)
5
<class 'numpy.ndarray'>


In [10]:
# creating array of zeroes
a=np.zeros((3,3))
print(a)

#creating arrays of ones
b=np.ones((2,2))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [15]:
#creating identity matrix
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# creating matrix with same element
c=np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [18]:
# creating random matrix used in nueral networks
randomMatrix=np.random.random((3,2))
print(randomMatrix)

[[0.90269634 0.55405927]
 [0.69190348 0.19291435]
 [0.51898725 0.72280555]]
