###Hello World
-A
-B



In [5]:
print("Hi")
#Esc,Y,Shift+enter

Hi


In [6]:
#add new cell above cell
#Esc+A
#add cell below a given cell
#esc+B
#add descritpion about algo
#add ###Text -A-B 
#press esc+M+Shift+Enter


In [7]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(a.shape)
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.shape)


[1 2 3 4]
(4,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [8]:
np.dot(b,b.T)

array([[ 30,  70],
       [ 70, 174]])

In [13]:

#generate 5 numbers between 60 and 100
print(np.random.randint(60,100,5))

#generate random 2D matrix
matrix=np.random.randint(60,100,(5,5))
print(matrix)

#find min and max from matrxi
print(np.min(matrix))
print(np.max(matrix))

[81 63 83 99 93]
[[88 96 61 87 62]
 [64 88 76 86 66]
 [67 65 98 65 87]
 [89 89 83 77 65]
 [89 69 77 78 66]]
61
98


In [16]:
a=np.array([1,2,4,3,2,5,6,4,1,2])
print(a)
b=np.unique(a,return_counts=True)
print(b)
print(b[0])
print(b[1])

[1 2 4 3 2 5 6 4 1 2]
(array([1, 2, 3, 4, 5, 6]), array([2, 3, 1, 2, 1, 1]))
[1 2 3 4 5 6]
[2 3 1 2 1 1]


In [18]:
#to get index with high value
print(np.argmax(a))


6


In [20]:
#index with high frequency in b array
idx=np.argmax(b[1])
element=b[0][idx]
print(element)

2


In [22]:
#slicing of matrix
print(matrix)
matrix[2:4,1:3]
#to get matrix from 2 and 3 row and 1 and 2 column 

[[88 96 61 87 62]
 [64 88 76 86 66]
 [67 65 98 65 87]
 [89 89 83 77 65]
 [89 69 77 78 66]]


array([[65, 98],
       [89, 83]])